### ISSUE TITLE
Update code to PHP 7.4

### ISSUE THREAD

**Issue by fauVictor** [includable/php-pkpass#110]
Seems to be a good idea to move base code to the typed version thanks to PHP7.4

Maybe, it an be a good idea to implement PHP's exceptions to manage error. What do you think ?

**Comment by tschoffelen** [comment]
Yes that would be very helpful!

**Comment by fauVictor** [comment]
You can look a first version of all I add on the fork I did to work https://github.com/fauVictor/php-pkpass

At this time, I don't test it but I will !
