### ISSUE TITLE
How i can add thumanil@2x.png option

### ISSUE THREAD

**Issue by skjangid** [includable/php-pkpass#135]
I want to show user prpfile image in the wallet, the option is available when i pass thumnail@2x,png in node.js but how i can use in php ?

**Comment by tschoffelen** [comment]
You can use the `addFile` method to add files to your pass, like the example here:

https://github.com/includable/php-pkpass/blob/ee6df67e8d6d8be056227d7c19636431132d5046/examples/starbucks_sample/index.php#L75

**Comment by skjangid** [comment]
$pass->addFile function is allowing absolute image path ?

**Comment by tschoffelen** [comment]
It won't allow web image URLs, you'd have to first download them to the filesystem.

The function accepts either relative or absolute local paths:

```php
$pass->addFile('icon.png'); // icon.png in same folder as your script

// or:
$pass->addFile('/var/local/web/.../icon.png');
```
