### ISSUE TITLE
Wallet Orders

### ISSUE THREAD

**Issue by cjnewbs** [includable/php-pkpass#136]
### Summary
Not really an issue as such but thought this would be the best place to ask. I've been working on creating Wallet orders and got completely stuck with the signature generation. Thankfully I came across [this stackoverflow post](https://stackoverflow.com/questions/37010864/creating-a-pkcs-7-detached-signature-for-apple-wallet-passes-using-php) which pointed me in this direction and now am able to create files recognised by the wallet app.

It looks like Wallet Passes and Orders are quite similar with only some minor differences.

I was considering trying to create a backwards-compatible PR to upgrade this repo to support generation of orders too. Is this something you would be interested in or would you prefer to focus strictly on passes (in which case I will try create a new library to create distributable order packages)?

If you want to focus only on Passes feel free to close this issue.

**Comment by tschoffelen** [comment]
Hi Craig! Ah that's cool, I didn't realise that's how wallet orders worked! (if anyone else ends up reading this, [see here](https://developer.apple.com/documentation/walletorders))

We could certainly extend it, as long as we do it in a way that isn't confusing to devs wanting to create passes.

Maybe we should introduce a separate class called `PKOrder` or something similar for it? We could then create a base class that shares some of the signing logic.
