### ISSUE TITLE
sorry, your pass cannot be installed to Passbook at this time

### ISSUE THREAD

**Issue by usamajamil213** [includable/php-pkpass#138]
I encountered an issue where attempts to install a pass to Passbook were unsuccessful, resulting in the error message: "Sorry, your pass cannot be installed to Passbook at this time." This issue persists despite multiple attempts to install the pass.

**Comment by tschoffelen** [comment]
Hi @usamajamil213 - thanks for opening an issue. Have you managed to try the debugging steps [listed the README](https://github.com/includable/php-pkpass?tab=readme-ov-file#debugging-passes)? If you share the error messages the console shows here, we might be able to help you with next steps.

**Comment by usamajamil213** [comment]
`$pass = new PKPass('../storage/apple-wallet-config/Certificatesv2.p12', env('CERTIFICATE_PASSWORD'));
$data = [
    'description' => 'Demo pass',
    'formatVersion' => 1,
    'organizationName' => 'Flight Express',
    'passTypeIdentifier' => 'pass.com.test.qrwallet',
    'serialNumber' => '12345678',
    'teamIdentifier' => env('TEAM_IDENTIFIER'),
    'barcode' => [
        'format' => 'PKBarcodeFormatQR',
        'message' => 'Flight-GateF12-ID6643679AH7B',
        'messageEncoding' => 'iso-8859-1',
    ],
    'backgroundColor' => 'rgb(32,110,247)',
    'logoText' => 'Flight info',
    'relevantDate' => date('Y-m-d\TH:i:sP')
];
$pass->setData($data);

$file=file_get_contents('my-image-path');
$pass->addRemoteFile('my-image-path','icon.png');
$pass->addFile($file);
$t=  $pass->create(true);
dd($t);`

**Comment by tschoffelen** [comment]
Closing for now, as this seems to be an implementation specific issue.
