### ISSUE TITLE
Could not read Certificate File

### ISSUE THREAD

**Issue by g021670** [includable/php-pkpass#142]
Hello Everyone,

im trying to run the example.php but im getting the error:

**Fatal error: Uncaught PKPass\PKPassException: Could not read certificate file. This might be related to using an OpenSSL version that has deprecated some older hashes**

After searching im pretty sure that it has something to do with my Openssl version. Im Running an local Apache Server, with openssl 3.1.3. I have already edited my "openssl.cnf" File to the following:

[openssl_init]
providers = provider_sect
[provider_sect]
default = default_sect
legacy = legacy_sect
[default_sect]
activate = 1
[legacy_sect]
activate = 1

But im still getting the same error...

Does anyone have an idea?

**Comment by tschoffelen** [comment]
Are you sure the certificate file itself is valid?

Could you try to run the following command and share the output here?

```
openssl x509 -in [certfile] -noout -text
```

**Comment by g021670** [comment]
Hi @tschoffelen,

thank you for your reply.

i run the command and this is what i got:

openssl x509 -in path -noout -text
Enter pass phrase for PKCS12 import pass phrase:
Could not read certificate from path
F03B0000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:crypto\evp\evp_fetch.c:341:Global default library context, Algorithm (RC2-40-CBC : 0), Properties ()

for further information: i use the same certificate when running the provided apple signtool on my mac and it works just fine

**Comment by g021670** [comment]
i just found out that the certificate i use in the command is a is a .p12 certificate. Could this cause the error?

**Comment by g021670** [comment]
After all i found a solution. 

For everyone interested: I found out, that the xamp server did not have a legacy.dll included. After i downloaded that and configured the OPENSSL_MODULES into environment variables, i could successfully use -legacy param to use "https://stackoverflow.com/questions/72598983/curl-openssl-error-error0308010cdigital-envelope-routinesunsupported" tutorial and create a new .p12 certificate.

**Comment by Robertbaelde** [comment]
I found this answer on Reddit that gave a better solution to this problem, instead of enabling legacy options with openssl you could simply re-generate your .p12 cert using these commands: 

`openssl pkcs12 -legacy -in key.p12 -nodes -out key_decrypted.tmp`

`openssl pkcs12 -in key_decrypted.tmp -export -out key_new.p12`

[source](https://www.reddit.com/r/PHPhelp/comments/11xyevb/comment/k7ezhaz/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)
