### ISSUE TITLE
Unable to track orders in Apple Wallet

### ISSUE THREAD

**Issue by brianapriletti** [includable/php-pkpass#144]
Hi, i'm currently trying to make an order display on the Apple Wallet App but i can't. I've followed the FinanceOrderTest.php file and it just won't work, i even tried to set myself the mimetype and all the headers of the response event though they are all set in the FinanceOrder.php file but in this way my iphone displays the error: "Cannot keep track of the order due to an invalid format".

**Comment by xitude** [comment]
Did you solve this?
